name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - jupyterlab=4.0.7
  - seaborn=0.13.0
  - pandas=1.3.5
  - pip=23.3.1
  - notebook=7.0.6
  - ipywidgets
  - pandas-profiling=2.11.0
  - pyarrow
  - jinja2=3.0.3
  - pip:
      - wandb==0.15.12