name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow=2.8.0
  - ipython=8.17.2
  - notebook=7.0.6
  - jupyterlab=4.0.7
  - cookiecutter=2.4.0
  - hydra-core=1.3.2
  - matplotlib=3.8.0
  - pandas=1.3.5
  - git=2.42.0
  - pip=23.3.1
  - pip:
      - wandb==0.15.12
