channels:
- conda-forge
dependencies:
- python=3.9.18
- pip<=20.3.3
- pip:
  - mlflow==2.8.0
  - cloudpickle==2.2.1
  - numpy==1.26.0
  - packaging==23.2
  - pandas==1.2.3
  - psutil==5.9.5
  - pyyaml==6.0.1
  - scikit-learn==1.3.2
  - scipy==1.11.3
name: mlflow-env
