name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.2.3
  - pip=20.3.3
  - mlflow=2.8.0
  - scikit-learn=1.3.2
  - matplotlib=3.8.1
  - pillow=8.1.2
  - pip:
      - wandb==0.10.31
